meta:
  name: Music Generation
  description: Generate music from a prompt and duration.
  id: MusicGenerator
  version: 0.1.0
  author: Tutopanda
  license: MIT

inputs:
  - name: Prompt
    description: Prompt text for the music generator.
    type: string
    required: true
  - name: Duration
    description: Desired length of the music audio in seconds.
    type: int
    required: true

artifacts:
  - name: Music
    description: Composed music for the movie.
    type: audio

connections:
  - from: Prompt
    to: MusicProducer
  - from: Duration
    to: MusicProducer
  - from: MusicProducer
    to: Music

producers:
  - name: MusicProducer
    provider: replicate
    model: stability-ai/stable-audio-2.5
    config:
      steps: 8
      cfg_scale: 1
    sdkMapping:
      Prompt:
        field: prompt
        type: string
        required: true
      Duration:
        field: duration
        type: int
        required: true
    outputs:
      Music:
        type: audio
        mimeType: audio/mp3
