meta:
  name: Video Prompt Generation
  description: Generate video generation prompt.
  id: VideoPromptGenerator
  version: 0.1.0
  author: Tutopanda
  license: MIT

inputs:
  - name: NarrativeText
    description: The narrative text to generate prompts for.
    type: string
    required: true
  - name: MovieSummary
    description: The movie summary to help generate prompt for a video that best reflects the given segment.
    type: string
    required: true
  - name: VideoStyle
    description: Desired musical style to feed into prompt.
    type: string
    required: true
  - name: SegmentDuration
    description: The per-segment video duration in seconds.
    type: int
    required: false
    default: 10
  - name: Audience
    description: Intended audience for tailoring details.
    type: string
    required: false
    default: adult

artifacts:
  - name: VideoPrompt
    description: Generated video prompts for the downstream video generation.
    type: string

connections:
  - from: NarrativeText
    to: VideoPromptProducer
  - from: MovieSummary
    to: VideoPromptProducer
  - from: VideoStyle
    to: VideoPromptProducer
  - from: Audience
    to: VideoPromptProducer
  - from: SegmentDuration
    to: VideoPromptProducer

  - from: VideoPromptProducer
    to: VideoPrompt

producers:
  - name: VideoPromptProducer
    provider: openai
    promptFile: ./prompts/video-prompt-producer.toml
