meta:
  name: Music Generation
  description: Generate music from a prompt and duration.
  id: MusicProducer
  version: 0.1.0
  author: Tutopanda
  license: MIT

inputs:
  - name: Prompt
    description: Prompt text for the music generator.
    type: string
    required: true
  - name: Duration
    description: Desired length of the music audio in seconds or miliseconds depending on model.
    type: int
    required: true

artifacts:
  - name: Music
    description: Composed music for the movie.
    type: audio

models:    
  - model: stability-ai/stable-audio-2.5
    provider: replicate
    inputSchema: ./schemas/stable-audio.json
    inputs:
      Prompt: prompt
      Duration: duration
    outputs:
      Music:
        type: audio
        mimeType: audio/mp3
  - model: elevenlabs/music
    provider: replicate
    inputSchema: ./schemas/elevenlabs-music.json
    inputs:
      Prompt: prompt
      Duration: music_length_ms
    outputs:
      Music:
        type: audio
        mimeType: audio/mp3
