inputs:
  InquiryPrompt: "Tell me about Battle of Waterloo"
  Duration: 30
  NumOfSegments: 2
  NumOfImagesPerNarrative: 2
  VoiceId: "Wise_Woman"
  ImageStyle: "Ghibli"
  VideoStyle: "Ghibli"
  SegmentDuration: 10
  Size: "1K"
  AspectRatio: "16:9"
  Resolution: "480p"
  MovieStyle: "Ghibli"
